comment:
  layout: "diff, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: false
  hide_project_coverage: false
coverage:
  status:
    project:
      default:
        target: auto
        # Max. allowed drop in coverage of the entire project.
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        # Max. allowed drop in coverage of modified lines.
        threshold: 60%
        informational: true
