/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.android.gnd.model;

import androidx.annotation.NonNull;
import com.google.auto.value.AutoValue;
import java.util.Date;
import java8.util.Optional;

/** User details and timestamp for creation or modification of a model object. */
@AutoValue
public abstract class AuditInfo {

  /**
   * Returns the user initiating the related action. This can never be null, since users must always
   * be logged in to make changes.
   */
  @NonNull
  public abstract User getUser();

  /** Returns the time at which the user action was initiated, according to the user's device. */
  @NonNull
  public abstract Date getClientTimestamp();

  /**
   * Returns the time at which the server received the requested change according to the server's
   * internal clock, or empty if the updated server time was not yet received.
   */
  @NonNull
  public abstract Optional<Date> getServerTimestamp();

  /** Returns a new instance initialized with the current client time and the specified user. */
  @NonNull
  public static AuditInfo now(User user) {
    return AuditInfo.builder().setUser(user).setClientTimestamp(new Date()).build();
  }

  // Generated by AutoValue plugin:

  public static Builder builder() {
    return new AutoValue_AuditInfo.Builder().setServerTimestamp(Optional.empty());
  }

  @AutoValue.Builder
  public abstract static class Builder {

    public abstract Builder setUser(User newUser);

    public abstract Builder setClientTimestamp(@NonNull Date newClientTimestamp);

    public abstract Builder setServerTimestamp(@NonNull Optional<Date> newServerTimestamp);

    @NonNull
    public abstract AuditInfo build();
  }
}
