package com.google.android.gnd.model;

import com.google.auto.value.AutoValue;

/** Represents a single application user. */
@AutoValue
public abstract class Terms {

  public abstract String getId();

  public abstract String getTerms();

  // Auto-generated by Android Studio AutoValue plugin.

  public static Builder builder() {
    return new AutoValue_Terms.Builder();
  }

  @AutoValue.Builder
  public abstract static class Builder {

    public abstract Builder setId(String newId);

    public abstract Builder setTerms(String terms);

    public abstract Terms build();
  }
}
