package com.google.android.gnd.model;

import com.google.auto.value.AutoValue;

/** Represents a single application user. */
@AutoValue
public abstract class User {

  public abstract String getId();

  public abstract String getEmail();

  public abstract String getDisplayName();

  // Auto-generated by Android Studio AutoValue plugin.

  public static Builder builder() {
    return new AutoValue_User.Builder();
  }

  @AutoValue.Builder
  public abstract static class Builder {

    public abstract Builder setId(String newId);

    public abstract Builder setEmail(String newEmail);

    public abstract Builder setDisplayName(String newDisplayName);

    public abstract User build();
  }
}
