/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.android.ground.model;

import com.google.auto.value.AutoValue;

/** Represents a single application user. */
@AutoValue
public abstract class User {

  public abstract String getId();

  public abstract String getEmail();

  public abstract String getDisplayName();

  // Auto-generated by Android Studio AutoValue plugin.

  public static Builder builder() {
    return new AutoValue_User.Builder();
  }

  @AutoValue.Builder
  public abstract static class Builder {

    public abstract Builder setId(String newId);

    public abstract Builder setEmail(String newEmail);

    public abstract Builder setDisplayName(String newDisplayName);

    public abstract User build();
  }
}
