# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: Run all tests in the e2eTest module

inputs:
  android-repository:
    description: 'ground-android repository under test'
    default: google/ground-android

  upload-artifacts:
    description: 'Whether to upload the final emulator data artifacts'
    default: 'false'

  google-maps-key:
    description: 'A Google Maps API key'

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        repository: ${{ inputs.android-repository }}
        clean: false

    - name: Check Firebase emulator connection
      shell: bash
      run: |
        echo "Checking connection to Firebase emulator..."
        if curl -v http://localhost:4000; then
            echo "Successfully connected to Firebase emulator!"
        else
            echo "Failed to connect to Firebase emulator (http://localhost:4000)"
            exit 1
        fi

    - name: Validate and setup MAPS_API_KEY
      env:
        MAPS_API_KEY: ${{ inputs.google-maps-key }}
      shell: bash
      run: |
        if [ -z "${MAPS_API_KEY}" ]; then
          echo "MAPS_API_KEY is missing from GitHub secrets"
          exit 1
        fi
        echo "MAPS_API_KEY is set"
        echo "MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}" > secrets.properties

    - name: Enable KVM group perms
      shell: bash
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: Setup JDK 17
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Gradle cache
      uses: gradle/actions/setup-gradle@v5

    - name: Run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: google_apis
        arch: x86_64
        emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        script: |
          adb wait-for-device
          adb emu geo fix -122.084 37.422
          sleep 2
          ./gradlew connectedLocalDebugAndroidTest --stacktrace

    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v6
      with:
        name: test-reports
        path: '**/build/reports/androidTests'
        retention-days: 7
        if-no-files-found: warn

    - name: Upload test screenshots
      if: always()
      uses: actions/upload-artifact@v6
      with:
        name: test-screenshots
        path: '**/build/outputs/connected_android_test_additional_output'
        retention-days: 7
        if-no-files-found: ignore

    - name: Export Firebase emulator data
      if: always()
      shell: bash
      run: |
        echo "Exporting emulator data..."
        npx -y -p firebase-tools firebase emulators:export ${{ github.workspace }}/test-android-result --project demo-local --force

    - name: Upload Firebase emulator data
      if: always() && inputs.upload-artifacts == 'true'
      uses: actions/upload-artifact@v6
      with:
        name: firebase-emulator-data
        path: ${{ github.workspace }}/test-android-result
        retention-days: 7
        if-no-files-found: warn
