#
# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Configures build of Docker images with Android SDK. To build and upload to Google Cloud:
#
# $ gcloud builds submit --config=cloudbuild.yaml --substitutions=_ANDROID_VERSION=28
#
# Based on https://github.com/GoogleCloudPlatform/cloud-builders-community

steps:

  # Debian Docker image with commonly used and Android specific dependencies.
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '--tag=gcr.io/$PROJECT_ID/android:base'
      - '--file=Dockerfile-base'
      - '.'

  # Above generated Docker image +and Android SDK.
  # To create multiple Android versions, use _ANDROID_VERSION=<android version> as mentioned above.
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '--tag=gcr.io/$PROJECT_ID/android:${_ANDROID_VERSION}'
      - '--build-arg'
      - 'android_version=${_ANDROID_VERSION}'
      - '--build-arg'
      - 'project_id=$PROJECT_ID'
      - '--file=Dockerfile-sdk'
      - '.'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/android:base'

images:
  - 'gcr.io/$PROJECT_ID/android:base'
  - 'gcr.io/$PROJECT_ID/android:${_ANDROID_VERSION}'

timeout: 2000s
