#
# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Defines base Docker container with commonly used and Android specific dependencies.
#
# This doesn't include the Android SDK.
#
# Based on https://github.com/GoogleCloudPlatform/cloud-builders-community

# We use openjdk13 rather than gcr.io/cloud-builders/javac because of
# https://bugs.openjdk.java.net/browse/JDK-8233655
FROM adoptopenjdk/openjdk13

ENV DEBIAN_FRONTEND=noninteractive

# Make Apt non-interactive.
RUN echo 'APT::Get::Assume-Yes "true";' > /etc/apt/apt.conf.d/90builder \
  && echo 'DPkg::Options "--force-confnew";' >> /etc/apt/apt.conf.d/90builder

# Install dependencies.
RUN apt-get update && \
    apt-get install -y \
        git locales sudo openssh-client ca-certificates tar gzip parallel \
        zip unzip bzip2 gnupg curl wget

# Install Google Cloud SDK
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && apt-get update -y && apt-get install google-cloud-sdk -y

# Set timezone to UTC by default.
RUN ln -sf /usr/share/zoneinfo/Etc/UTC /etc/localtime

# Use Unicode.
RUN locale-gen C.UTF-8 || true
ENV LANG=C.UTF-8

ARG sdk_version=commandlinetools-linux-6858069_latest.zip
ARG android_home=/opt/android/sdk

# Install Android SDK.
RUN sudo mkdir -p ${android_home} && \
    curl --silent --show-error --location --fail --retry 3 --output /tmp/${sdk_version} https://dl.google.com/android/repository/${sdk_version} && \
    unzip -q /tmp/${sdk_version} -d ${android_home} && \
    rm /tmp/${sdk_version}

# Set environment variables.
ENV ANDROID_HOME ${android_home}
ENV ADB_INSTALL_TIMEOUT 120
ENV PATH=${ANDROID_HOME}/emulator:${ANDROID_HOME}/cmdline-tools:${ANDROID_HOME}/cmdline-tools/bin:${ANDROID_HOME}/platform-tools:${PATH}

RUN mkdir ~/.android && echo '### User Sources for Android SDK Manager' > ~/.android/repositories.cfg

RUN yes | sdkmanager --licenses --sdk_root=${ANDROID_HOME} && sdkmanager --update --sdk_root=${ANDROID_HOME}

# Update SDK manager and install system image, platform and build tools.
RUN yes | sdkmanager \
    --sdk_root=${ANDROID_HOME} \
    "tools" \
    "platform-tools" \
    "extras;android;m2repository" \
    "extras;google;m2repository" \
    "extras;google;google_play_services" \
    "build-tools;29.0.2"

ENTRYPOINT ["bash"]
